### ISSUE TITLE
Plugin no longer works

### ISSUE THREAD

**Issue by Nericu** [dwhitacre/WindowsGSM.ForgeMC#14] opened 2022-08-23 05:06 UTC
Plugin just give the following error in windowsgsm 
"Fail to install [ERROR] The remote server returned an error: (410) Gone.

Any chance this can be updated/resolved?

**Comment by Nericu** [comment] 2022-08-23 05:08
Also it looks like someone made a fork of the plugin that mostly resolves this issue
- however it still fails to fully create the server in windowgsm for no give reason.

https://github.com/Ada64bit/WindowsGSM.ForgeMC

**Comment by dwhitacre** [comment] 2022-09-13 21:39
hey, this appears to be a duplicate of #13, so I am going to close this issue. 

fwiw, I don't really have any plans to update this repo myself. I am happy to have @Ada64bit create a PR to merge their changes into this repo, and add them as a contributor.

**Closed as completed by dwhitacre** 2022-09-13 21:39 UTC
Labels: duplicate
